In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
land_area = [1500, 2000, 1800, 2500, 2200, 1600, 1900, 2100, 2300, 2700,
             1400, 2600, 2800, 2000, 2400, 1700, 2900, 1800, 1500, 2100,
             2300, 2700, 1900, 2200, 1600, 2500, 2000, 2800, 2400, 1700,
             2600, 1800, 2100, 1900, 2300, 2700, 1500, 2200, 1600, 2000,
             2400, 1700, 2500, 1800, 2100, 1900, 2300, 2700]

bedrooms = [2, 3, 2, 4, 3, 2, 3, 4, 3, 4,
            2, 3, 4, 2, 3, 2, 4, 3, 2, 3,
            4, 3, 2, 3, 4, 2, 3, 4, 2, 3,
            4, 2, 3, 4, 2, 3, 4, 2, 3, 4,
            2, 3, 4, 2, 3, 4, 2, 3]

price = [100000, 150000, 120000, 200000, 170000, 110000, 130000, 180000, 160000, 220000,
         95000, 175000, 230000, 125000, 165000, 115000, 240000, 140000, 105000, 155000,
         190000, 175000, 130000, 160000, 195000, 135000, 170000, 210000, 145000, 135000,
         200000, 110000, 150000, 185000, 120000, 165000, 210000, 140000, 145000, 200000,
         125000, 155000, 220000, 130000, 175000, 185000, 120000, 160000]

house_data = {
    'Land_Area (sqft)': land_area,
    'Bedrooms': bedrooms,
    'House_Price (x1000 $)': price
}


In [3]:
df=pd.DataFrame(house_data)
df.head()

Land_Area (sqft)  Bedrooms  House_Price (x1000 $)
0              1500         2                 100000
1              2000         3                 150000
2              1800         2                 120000
3              2500         4                 200000
4              2200         3                 170000

# Lets Visualize Our Data

In [4]:
import plotly.express as px
import pandas as pd


# Creating 3D scatter plot using Plotly Express
fig = px.scatter_3d(df, x='Land_Area (sqft)', y='Bedrooms', z='House_Price (x1000 $)',
                    title='3D Scatter Plot of House Prices',
                    labels={'Land_Area (sqft)': 'Land Area (sqft)', 'Bedrooms': 'Bedrooms', 'House_Price (x1000 $)': 'House Price (x1000 $)'},)

fig.update_layout(scene=dict(
                    xaxis_title='Land Area (sqft)',
                    yaxis_title='Bedrooms',
                    zaxis_title='House Price (x1000 $)'),
                    width=700)
fig.show()




   ### **Lets Apply OLS Method to Calculate the price of New Inputted Area and no of Bedroom**
   <br>

**The multiple Linear Equation is given by *Y = M1x1+M2x2+....Mnxn+ C***

<br>

**we have to Calculate B hat which is all coefficients (M1 to Mn and c)**
<br><br>

$$\hat{\boldsymbol{\beta}} =(\mathbf{X}^T\mathbf{X})^{-1} \mathbf{X}^T\mathbf{y}$$


In [5]:
# Small Concept

a=[[3,2,3],
   [7,2,3],
   [9,2,3]]

X_Stacked = np.column_stack((np.ones(len(a)), a))

print(X_Stacked) # a ko aagai sabai 1 aauxa column wise adding ones

[[1. 3. 2. 3.]
 [1. 7. 2. 3.]
 [1. 9. 2. 3.]]


In [6]:
def multipleLinearRegression_Predection(X,y):

    X=X # all feature data column data

    X=np.column_stack((np.ones(len(X)), X)) #stacking ones to column wise

    y=y # all target  column data

    X_transpose=np.transpose(X)

    # -------------------------------for calculating betas value----------------------------------------

    betas= np.linalg.inv(X_transpose.dot(X)).dot(X_transpose).dot(y)

    # -------------------------------for calculating Y_hat predection--------------------------------

    y_hat= X.dot(betas)

    return betas,y_hat

In [7]:
x=df[['Land_Area (sqft)','Bedrooms']].values


y=df['House_Price (x1000 $)'].values

coeffs, Y_predictions = multipleLinearRegression_Predection(x,y)

print("The input features is:" ,x[:5])
print("The input features shape is:" ,x.shape)
print("The output features is:" ,y[:5])
print("The output features shape is:", y.shape)

The input features is: [[1500    2]
 [2000    3]
 [1800    2]
 [2500    4]
 [2200    3]]
The input features shape is: (48, 2)
The output features is: [100000 150000 120000 200000 170000]
The output features shape is: (48,)


In [8]:

print("The parameters are :",coeffs)
print("The Predections Prices of houses are: ",Y_predictions)


The parameters are : [-7.97332495e+03  2.64395900e+01  3.74005733e+04]
The Predections Prices of houses are:  [106487.20678004 157107.57513446 114419.08379095 207727.94348888
 162395.49314174 109131.16578368 154463.61613083 197152.10747434
 165039.45214537 213015.86149616 103843.24777641 172971.32915628
 215659.82049979 119707.00179823 167683.41114901 111775.12478732
 218303.77950343 151819.65712719 106487.20678004 159751.5341381
 202440.02548161 175615.28815992 117063.04279459 162395.49314174
 183932.31245615 132926.79681641 157107.57513446 215659.82049979
 130282.83781277 149175.69812355 210371.90249252 114419.08379095
 159751.5341381  191864.18946706 127638.87880914 175615.28815992
 181288.35345252 124994.9198055  146531.73911992 194508.1484707
 130282.83781277 149175.69812355 207727.94348888 114419.08379095
 159751.5341381  191864.18946706 127638.87880914 175615.28815992]


# Lets Predict the price of house having area 2800 sqft and rooms 4

In [10]:
# Test prediction for a specific case
X_test = np.array([[2800, 4]])
X_test = np.column_stack((np.ones(len(X_test)), X_test))
y_prediction_test = X_test.dot(coeffs)

print("The price of a house having area 1500 sqft and 2 rooms is:", y_prediction_test, "$")


The price of a house having area 1500 sqft and 2 rooms is: [215659.82049979] $
